name: CD Pipeline

on:
  workflow-run:
    workflows: ["CI Pipeline"]
    types:
      - completed # CD will be triggered when CI workflow will be successfully completed 

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Access to the prod server and Deploy through SSH
      - name: Deploy to Production via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # saving the values for the prod server and Docker compose: token for GHCR and tag of the newest image
            # head_sha is the tag which was pushed by CI
            export GHCR_TOKEN=${{ secrets.GHCR_TOKEN }}
            export IMAGE_TAG=${{ github.event.workflow_run.head_sha }}

            # Run the server deploy script
            bash ~/Deployment/deploy.sh

